

services:
  broker:
    image: zookeeper:latest
    networks:
      - kafka_network
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092   # 使用服务名代替 IP 地址
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  # 连接到 ZooKeeper 容器
      ALLOW_PLAINTEXT_LISTENER: "yes"   # 允许 PLAINTEXT 监听
    restart: always

  zookeeper:
    image: a_zookeeper:latest
    volumes:
      - /home/user1/code/kafka/KafkaManager01/zookeeper-data:/bitnami/zookeeper
    networks:
      - kafka_network
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=4000     # 增加 tickTime
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=5      # 增加 syncLimit
      - ALLOW_ANONYMOUS_LOGIN=yes   # 允许匿名登录
      - ZOOKEEPER_ENABLE_UI=yes  # 启用 Web UI
    ports:
      - "2181:2181"
      - "8080:8080"  # Web UI 端口
    restart: always

  kafdrop:
    image: a_kafdrop:latest
    networks:
      - kafka_network
    container_name: kafka_ui
    environment:
      - KAFKA_BROKERCONNECT=broker:9092  # 连接 Kafka Broker 服务
      - ZOOKEEPER_CONNECT=zookeeper:2181  # ZooKeeper 服务地址
    

    ports:
      - 9000:9000
    depends_on:
      - broker
      - zookeeper

    restart: always

networks:
  kafka_network:
    driver: bridge
